# Generated by Django 5.1 on 2024-12-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='response',
            field=models.CharField(max_length=20, null=True, verbose_name='response'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='responsed_at',
            field=models.DateTimeField(null=True, verbose_name='respondido em'),
        ),
    ]
